services:
  srs:
    image: ossrs/srs:5 # 或者使用 ossrs/srs:6
    container_name: srs_media_server
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP-FLV / HLS
      - "1985:1985" # HTTP API
      - "8000:8000/udp" # WebRTC over UDP (如果需要 WebRTC)
      - "1990:1990" # Prometheus Exporter (可选)
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf # 挂载配置文件
    restart: always

# 如果后端和数据库也需要通过 Docker 管理，可以在这里添加：
# backend:
#   build: ./backend
#   ports:
#     - "5000:5000"
#   depends_on:
#     - mongo
#   environment:
#     - MONGO_URI=mongodb://mongo:27017/twitch-clone
#     - JWT_SECRET=your_very_secret_key
#     - PORT=5000
# 
# mongo:
#   image: mongo:latest
#   container_name: mongodb
#   ports:
#     - "27017:27017"
#   volumes:
#     - mongo_data:/data/db

# volumes:
#   mongo_data: 
