services:
  srs:
    image: ossrs/srs:6 # 或者使用 ossrs/srs:6
    container_name: srs_media_server
    network_mode: "host"  # 使用主机网络模式
    # ports部分在host模式下不需要，可以注释掉
    # ports:
    #   - "1935:1935" # RTMP
    #   - "8080:8080" # HTTP-FLV, HLS
    #   - "1985:1985" # HTTP API
    #   - "8000:8000/udp" # WebRTC over UDP
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf # 挂载配置文件
    restart: always

# 如果后端和数据库也需要通过 Docker 管理，可以在这里添加：
# backend:
#   build: ./backend
#   ports:
#     - "5000:5000"
#   depends_on:
#     - mongo
#   environment:
#     - MONGO_URI=mongodb://mongo:27017/twitch-clone
#     - JWT_SECRET=your_very_secret_key
#     - PORT=5000
# 
# mongo:
#   container_name: mongodb
#   ports:
#     - "27017:27017"
#   volumes:
#     - mongo_data:/data/db

# volumes:
#   mongo_data: 
